'use strict'
const test=require('node:test'),assert=require('node:assert/strict')
const {createKnowledgeCore}=require('../src')
const core=createKnowledgeCore({approvedOnly:false})
test('官方武器目录只以 DE 快照和 Languages.bin 为事实来源',()=>{assert.ok(core.weapons.length>600);const pride=core.getWeapon('骄傲');assert.equal(pride.subject.canonical,'Pride');assert.equal(pride.subject.officialUniqueName,'/Lotus/Weapons/Tenno/Melee/HeavyScythe/TnOrionSiriusScythe/TnSiriusScytheWeapon');assert.equal(pride.weaponIdentity.equipmentType,'melee');assert.equal(typeof pride.weaponIdentity.omegaAttenuation,'number')})
test('官方产品分类边界保留真实武器并排除宠物构造部件',()=>{const catalog=require('../knowledge/generated/official-weapons.json'),names=new Set(catalog.weapons.map(item=>item.canonical));for(const name of ['Rumblejack','Sirocco','Catabolyst','Coda Catabolyst','Quatz','Spectra Vandal','Corufell'])assert.ok(names.has(name),`${name} 被错误排除`);assert.equal(catalog.weapons.filter(item=>/\/Types\/Friendly\/Pets\//.test(item.uniqueName)).length,0);assert.equal(catalog.weapons.filter(item=>['SpecialItems'].includes(item.productCategory)).length,0);assert.ok(catalog.weapons.filter(item=>item.equipmentType==='companion').every(item=>item.productCategory==='SentinelWeapons'))})
test('哈尔武由官方活动公告与简中语言记录编译为限时武器',()=>{const weapon=core.getWeapon('哈尔武'),result=core.getAcquisition('哈尔武');assert.equal(weapon.subject.canonical,'Haalvu');assert.equal(weapon.subject.officialUniqueName,'/Lotus/Weapons/Sentients/SentOctaMiniGun/SentOctaMiniGun');assert.equal(weapon.status,'complete');assert.match(result.description,/TennoCon 2026 官方直播掉宝期间可领取/);assert.match(result.description,/活动现已结束，当前没有常驻获取方式/);assert.equal(core.resolveItem('哈尔武').kind,'weapon')})
test('骄傲官方配方完整保留总图和三个部件引用',()=>{const pride=core.getWeapon('骄傲'),recipe=pride.recipes[0];assert.ok(recipe);assert.equal(recipe.outputQuantity,1);assert.equal(recipe.ingredients.length,3);assert.ok(pride.acquisition.routes.some(x=>x.scope==='blueprint'));assert.ok(pride.acquisition.routes.some(x=>x.scope==='components'));const crafting=pride.acquisition.routes.find(x=>x.scope==='components');assert.equal(crafting.requirements.recipeId,recipe.id);assert.equal(crafting.requirements.items,undefined);assert.ok(core.getAcquisition('骄傲').structuredMethods.every(x=>x.requirements&&Array.isArray(x.requirementLines)))})
test('正向配方唯一生成 byResult 和 byIngredient',()=>{const graph=core.weaponCraftingGraph,pride=core.getWeapon('骄傲');assert.equal(graph.recipesFor(pride.subject.officialUniqueName).length,1);for(const ingredient of pride.recipes[0].ingredients)assert.ok(graph.craftTo(ingredient.uniqueName).some(x=>x.resultUniqueName===pride.subject.officialUniqueName))})
test('武器解析使用共享评分器，合成支持多个输入和名称标点',()=>{assert.equal(core.resolveWeapon('骄傲').canonical,'Pride');const parsed=core.parseWeaponCraftingCommand('合成 骄傲、Cernos');assert.equal(parsed.items.length,2);assert.match(core.renderWeaponCraftingCommand('合成 骄傲'),/如何合成/);assert.equal(core.parseWeaponCraftingCommand('今天合成点什么'),null)})
test('官方任务表按每个任务标题切换，不把骄傲错误继承到水星',()=>{const pride=core.getWeapon('骄傲'),blueprint=pride.acquisition.routes.find(x=>x.scope==='blueprint');assert.ok(blueprint.methods.some(x=>x.sourceCanonical==='Uranus/The Kuva Wytch (Skirmish)'&&x.locationId==='mission.the-kuva-wytch'&&x.missionTypeId==='mission-type.skirmish'&&x.chance===0.1429));assert.ok(blueprint.methods.every(x=>x.sourceCanonical!=='Mercury/Apollodorus (Survival)'))})
test('骄傲由舰船任务和 Hunhow 官方报价完整闭环',()=>{const pride=core.getWeapon('骄傲'),result=core.getAcquisition('骄傲');assert.equal(pride.status,'complete');const blueprint=pride.acquisition.routes.find(x=>x.scope==='blueprint'),exchange=blueprint.methods.find(x=>x.type==='vendor-exchange');assert.equal(exchange.npcId,'npc.hunhow');assert.equal(exchange.locationId,'hub.pontis-tower');assert.equal(exchange.requirements.currency[0].currencyId,'currency.emerald-talent');assert.equal(exchange.requirements.currency[0].amount,90);assert.match(result.description,/总图：完成赤毒女巫号（前哨战）概率获得/);assert.match(result.description,/在渡界之塔找Hunhow兑换，需要90个翠绿天赋/);assert.match(result.description,/愤怒 刀刃：完成火山石天使号（前哨战）概率获得/);assert.doesNotMatch(result.description,/水星|边界之塔/)})
test('禁止依据 excludeFromMarket 猜商城来源或完整状态',()=>{const braton=core.getWeapon('布莱顿'),blueprint=braton.acquisition.routes.find(x=>x.scope==='blueprint');assert.equal(braton.status,'review-required');assert.ok(!blueprint.methods.some(x=>x.type==='market-purchase'));assert.match(core.getAcquisition('布莱顿').description,/尚未由 DE 官方结构闭环：总图来源/)})
test('舍杜由官方任务、掉落表、配方和简中描述闭环',()=>{const shedu=core.getWeapon('舍杜'),result=core.getAcquisition('舍杜');assert.equal(shedu.status,'complete');assert.equal(shedu.description.localizationStatus,'official-zh');assert.equal(shedu.acquisition.routes.find(x=>x.scope==='blueprint').methods[0].questCanonical,'Erra');const parts=shedu.acquisition.routes.filter(x=>x.scope==='component');assert.equal(parts.length,4);assert.ok(parts.every(x=>x.status==='complete'&&x.methods[0].sourceDisplayName==='共生使'&&x.methods[0].chance===0.01));assert.match(result.description,/总图：完成任务「Erra」获得/);assert.match(result.description,/舍杜 枪管、机体、握柄、枪机：击败共生使概率获得/);assert.doesNotMatch(result.description,/尚未由 DE 官方结构闭环/)})
test('葬铭从官方虚空风暴奖励补充表编译总图与部件来源',()=>{const epitaph=core.getWeapon('葬铭'),result=core.getAcquisition('葬铭');const blueprint=epitaph.acquisition.routes.find(x=>x.scope==='blueprint'),parts=epitaph.acquisition.routes.filter(x=>x.scope==='component');assert.equal(blueprint.status,'complete');assert.equal(parts.length,2);assert.ok(parts.every(x=>x.status==='complete'));assert.match(result.description,/总图与部件：完成九重天地球、金星、土星比邻星虚空风暴概率获得/);assert.doesNotMatch(result.description,/9\.52%|10%|葬铭 枪管|葬铭 枪机/);assert.doesNotMatch(result.description,/WraithSidearm/)});
test('同一总图的同概率替代敌人合并但不同掉落机制保持独立',()=>{const text=core.getAcquisition('阿利乌双枪').description;assert.match(text,/总图：击败爆破型痈裂者、爆破型奔跳者、爆破型疾冲者概率获得/);assert.match(text,/总图：击败爆破型巨兽概率获得/);assert.doesNotMatch(text,/%/) });
test('Prime 武器复用状态框架且特殊 Prime 不伪装成遗物来源',()=>{const current=core.getWeapon('塞多 Prime'),currentText=core.getAcquisition('塞多 Prime').description,vaulted=core.getWeapon('黑鸦 Prime'),vaultedText=core.getAcquisition('黑鸦 Prime').description,sagek=core.getWeapon('杀格 Prime'),sagekText=core.getAcquisition('杀格 Prime').description;assert.equal(current.acquisition.prime.kind,'prime-relic');assert.equal(current.acquisition.prime.status,'当前出库');assert.match(currentText,/Prime 状态：当前出库/);assert.match(currentText,/总图：中纪 C9（金）/);assert.match(currentText,/枪机：古纪 K12（银）；古纪 Q3（银）/);assert.equal(vaulted.acquisition.prime.status,'已入库');assert.match(vaultedText,/当前已入库/);assert.equal(sagek.acquisition.prime.kind,'special-prime');assert.match(sagekText,/佩里塔叛乱/);assert.doesNotMatch(sagekText,/遗物|已入库|Prime 状态/)});
test('刷武器不把空泛制造句当作获取来源且配方仍供合成查询使用',()=>{for(const entry of core.weapons){const output=core.getAcquisition(entry.subject.canonical).description;assert.doesNotMatch(output,/(?:^|\n)制造[^\n]+/)}assert.match(core.renderWeaponCraftingCommand('合成 葬铭'),/葬铭如何合成：葬铭 枪管 ×1、葬铭 枪机 ×1/)})
test('Simaris 武器来源从原始分类全量编译且未知规则保持待审',()=>{const index=require('../generated/simaris-weapon-source-index.json');assert.equal(index.counts.weapons,18);assert.equal(index.counts.records,21);assert.equal(index.counts.approved,13);assert.equal(index.counts.reviewRequired,8);for(const records of Object.values(index.byWeapon))for(const record of records){assert.match(record.sourceCanonical,/^Cephalon Simaris/);if(record.reviewStatus==='approved'){assert.equal(record.kind,'quest-repurchase');assert.ok(record.unlockId&&record.unlockDisplayName)}else assert.ok(['standing-shop','daily-tribute-repurchase','glassmaker-repurchase','unresolved-simaris'].includes(record.kind))}})
test('全部已批准 Simaris 武器记录均接入对应层级的任务首获和后续回购',()=>{const index=require('../generated/simaris-weapon-source-index.json');for(const records of Object.values(index.byWeapon)){const approved=records.filter(record=>record.reviewStatus==='approved');if(!approved.length)continue;const weapon=core.getWeapon(approved[0].weaponCanonical);if(!weapon)continue;for(const record of approved){const route=weapon.acquisition.routes.find(candidate=>candidate.scope===record.scope&&(!record.partUniqueName||candidate.partRefs.includes(record.partUniqueName)));assert.ok(route,`${record.weaponCanonical} ${record.scope} 缺 route`);assert.ok(route.methods.some(method=>method.type==='quest-reward'&&method.questDisplayName===record.unlockDisplayName));assert.ok(route.methods.some(method=>method.type==='vendor-exchange'&&method.npcId==='npc.cephalon-simaris'))}}const nataruk=core.getAcquisition('太始弓').description;assert.match(nataruk,/成品：完成任务「新纪之战」获得/);assert.match(nataruk,/成品：在任意中继站兑换/)})
test('DE 官方支持文档任务武器全部接入首获路线而不是逐武器补丁',()=>{const index=require('../generated/official-support-quest-weapon-index.json');assert.equal(index.counts.weapons,13);for(const records of Object.values(index.byWeapon))for(const record of records){const weapon=core.getWeapon(record.weaponCanonical),scopes=record.scope==='blueprint-and-components'?['blueprint',...weapon.acquisition.routes.filter(route=>route.scope==='component').map(()=> 'component')]:[record.scope];for(const scope of new Set(scopes)){const routes=weapon.acquisition.routes.filter(route=>route.scope===scope);assert.ok(routes.some(route=>route.methods.some(method=>method.type==='quest-reward'&&method.questDisplayName===record.questDisplayName)),`${record.weaponCanonical} 缺 ${record.questDisplayName} ${scope} 路线`)}}const broken=core.getAcquisition('破碎的战争之剑').description;assert.match(broken,/成品：完成任务「第二场梦」获得/);assert.match(broken,/总图：击败黑影追猎者、卫护追猎者概率获得/);assert.doesNotMatch(broken,/尚未由 DE 官方结构闭环：成品来源/)});
test('驱魔之刃完整显示僵局协议首获与 Simaris 后续回购',()=>{const xoris=core.getWeapon('驱魔之刃'),text=core.getAcquisition('驱魔之刃').description,craft=core.renderWeaponCraftingCommand('合成 驱魔之刃');assert.equal(xoris.status,'complete');assert.ok(xoris.acquisition.routes.filter(route=>['blueprint','component'].includes(route.scope)).every(route=>route.status==='complete'&&route.methods.some(method=>method.type==='quest-reward')&&route.methods.some(method=>method.type==='vendor-exchange')));assert.match(text,/总图与部件：完成任务「僵局协议」获得；完成后可在任意中继站找中枢 Simaris 回购（总图 100,000 声望，各部件 15,000 声望）/);assert.doesNotMatch(text,/尚未由 DE 官方结构闭环|CrpGhostCatcher/);assert.match(craft,/驱魔之刃 刀刃 ×1、驱魔之刃 核心 ×1、驱魔之刃 握柄 ×1/)})
test('全量武器明确记录描述与适用获取链缺口',()=>{for(const entry of core.weapons){assert.ok(entry.coverage&&typeof entry.coverage.description==='boolean');assert.ok(Array.isArray(entry.coverage.components));assert.equal(entry.status==='complete',entry.coverage.auditedComplete);if(entry.status==='complete')assert.equal(entry.coverage.autoComplete,true);const output=core.getAcquisition(entry.subject.canonical).description;if(entry.status!=='complete')assert.match(output,/尚未由 DE 官方结构闭环|尚未完成逐项来源审计|ExportWeapons 尚未提供|官方简体中文武器描述暂缺/)}})
test('所有武器 route 与已装配 method 只使用共享 requirements 且不泄漏未本地化来源',()=>{for(const entry of core.weapons){for(const route of entry.acquisition.routes){assert.ok(route.requirements);assert.ok(['none','currency','standing','quest','item'].includes(route.requirements.type));for(const method of route.methods||[])if(method.reviewStatus==='approved'&&method.sourceCanonical)assert.ok(method.sourceDisplayName||method.locationId)}const result=core.getAcquisition(entry.subject.canonical);assert.ok(result);assert.ok(result.structuredMethods.every(m=>m.requirements&&Array.isArray(m.requirementLines)))}})
