'use strict'
const test=require('node:test'),assert=require('node:assert/strict')
const {createKnowledgeCore}=require('../src')
const core=createKnowledgeCore({approvedOnly:false})
test('官方语言中已发布但上游Mod快照缺失的强化Mod仍进入目录',()=>{const mod=core.getOfficialMod('刀锋迫击'),result=core.getAcquisition('刀锋迫击');assert.equal(mod.canonical,'Razor Mortar');assert.equal(mod.displayName,'刀锋迫击');assert.match(mod.provenance.source,/DE Languages\.bin/);assert.ok(['complete','review-required'].includes(mod.status));assert.match(result.description,/刀锋迫击/);assert.match(result.description,/中枢苏达/);assert.match(result.description,/佩兰数列/)});
test('官方武器目录只以 DE 快照和 Languages.bin 为事实来源',()=>{assert.ok(core.weapons.length>600);const pride=core.getWeapon('骄傲');assert.equal(pride.subject.canonical,'Pride');assert.equal(pride.subject.officialUniqueName,'/Lotus/Weapons/Tenno/Melee/HeavyScythe/TnOrionSiriusScythe/TnSiriusScytheWeapon');assert.equal(pride.weaponIdentity.equipmentType,'melee');assert.equal(typeof pride.weaponIdentity.omegaAttenuation,'number')})
test('官方产品分类边界保留真实武器并排除宠物构造部件',()=>{const catalog=require('../knowledge/generated/official-weapons.json'),names=new Set(catalog.weapons.map(item=>item.canonical));for(const name of ['Rumblejack','Sirocco','Catabolyst','Coda Catabolyst','Quatz','Spectra Vandal','Corufell'])assert.ok(names.has(name),`${name} 被错误排除`);assert.equal(catalog.weapons.filter(item=>/\/Types\/Friendly\/Pets\//.test(item.uniqueName)&&item.productCategory!=='SentinelWeapons').length,0);for(const name of ['Cryotra','Multron','Helstrum','Tazicor','Vulcax','Batoten','Lacerten','Akaten'])assert.ok(names.has(name),`${name} 被宠物路径粗略规则误排`);assert.equal(catalog.weapons.filter(item=>['SpecialItems'].includes(item.productCategory)).length,0);assert.ok(catalog.weapons.filter(item=>item.equipmentType==='companion').every(item=>item.productCategory==='SentinelWeapons'))})
test('哈尔武由官方活动公告与简中语言记录编译为限时武器',()=>{const weapon=core.getWeapon('哈尔武'),result=core.getAcquisition('哈尔武');assert.equal(weapon.subject.canonical,'Haalvu');assert.equal(weapon.subject.officialUniqueName,'/Lotus/Weapons/Sentients/SentOctaMiniGun/SentOctaMiniGun');assert.equal(weapon.status,'complete');assert.match(result.description,/TennoCon 2026 官方直播掉宝期间可领取/);assert.match(result.description,/活动现已结束，当前没有常驻获取方式/);assert.equal(core.resolveItem('哈尔武').kind,'weapon')})
test('骄傲官方配方完整保留总图和三个部件引用',()=>{const pride=core.getWeapon('骄傲'),recipe=pride.recipes[0];assert.ok(recipe);assert.equal(recipe.outputQuantity,1);assert.equal(recipe.ingredients.length,3);assert.ok(pride.acquisition.routes.some(x=>x.scope==='blueprint'));assert.ok(pride.acquisition.routes.some(x=>x.scope==='components'));const crafting=pride.acquisition.routes.find(x=>x.scope==='components');assert.equal(crafting.requirements.recipeId,recipe.id);assert.equal(crafting.requirements.items,undefined);assert.ok(core.getAcquisition('骄傲').structuredMethods.every(x=>x.requirements&&Array.isArray(x.requirementLines)))})
test('完整武器作为配方材料时按官方武器 ID 回连简中身份',()=>{const war=core.getWeapon('战争之剑'),recipe=war.recipes[0],broken=recipe.ingredients.find(item=>item.uniqueName==='/Lotus/Weapons/Tenno/Melee/Swords/StalkerTwo/StalkerTwoSmallSword');assert.equal(broken.displayName,'破碎的战争之剑');assert.equal(broken.localizationStatus,'official-zh');assert.equal(core.renderWeaponCraftingCommand('合成 战争之剑'),'这些武器不能用于合成其他武器');const catalogIds=new Set(core.weapons.map(item=>item.subject.officialUniqueName));for(const entry of core.weapons)for(const compiled of entry.recipes||[])for(const ingredient of compiled.ingredients)if(catalogIds.has(ingredient.uniqueName)){assert.equal(ingredient.localizationStatus,'official-zh');assert.ok(ingredient.displayName)}});
test('官方武器名称清除分类标记且配方耗时不泄漏原始秒数',()=>{for(const weapon of core.weapons){assert.doesNotMatch(weapon.subject.canonical,/<[^>]+>/);assert.doesNotMatch(weapon.subject.displayName,/<[^>]+>/);assert.doesNotMatch(core.renderWeaponCraftingCommand(`合成 ${weapon.subject.displayName}`)||'',/耗时 \d+ 秒/)}const flax=core.renderWeaponCraftingCommand('合成 弗拉克斯');assert.equal(flax,'1把弗拉克斯可合成为 克纳克斯');assert.doesNotMatch(flax,/<ARCHWING>/)});
test('正向配方唯一生成 byResult 和 byIngredient',()=>{const graph=core.weaponCraftingGraph,pride=core.getWeapon('骄傲');assert.equal(graph.recipesFor(pride.subject.officialUniqueName).length,1);for(const ingredient of pride.recipes[0].ingredients)assert.ok(graph.craftTo(ingredient.uniqueName).some(x=>x.resultUniqueName===pride.subject.officialUniqueName))})
test('截图与文字合成只输出武器参与的简洁句式',()=>{const uses=core.renderWeaponCraftingUses(['破碎的战争之剑','破碎的战争之剑']),command=core.renderWeaponCraftingCommand('合成 破碎的战争之剑');assert.equal(uses,'1把破碎的战争之剑可合成为 战争之剑');assert.equal(command,uses);assert.doesNotMatch(command,/可以用于合成什么|如何合成|制造费用|耗时|→|【/)})
test('审核武器黑话优先于弱拼音近似匹配',()=>{for(const alias of ['波棍','玻棍'])assert.equal(core.resolveWeapon(alias).canonical,'Bo Prime');for(const alias of ['赛多 Prime','赛多Prime']){const resolved=core.resolveWeapon(alias);assert.equal(resolved.canonical,'Cedo Prime');const item=core.getWeapon(resolved.canonical);assert.equal(item.subject.officialUniqueName,'/Lotus/Weapons/Tenno/LongGuns/PrimeCedo/PrimeCedoWeapon')}assert.equal(core.resolveWeapon('伯斯顿').canonical,'Burston');assert.equal(core.resolveWeapon('bosidun').canonical,'Burston')})
test('紫卡武器解析按官方中文、审核别名、英文与拼音分层并锁定精确短名',()=>{
  const tomb=core.resolveRivenWeapon('墓指');
  assert.equal(tomb.canonical,'Tombfinger');
  assert.equal(tomb.displayName,'墓指');
  assert.equal(tomb.officialUniqueName,'/Lotus/Weapons/SolarisUnited/Secondary/SUModularSecondarySet1/Barrel/SUModularSecondaryBarrelBPart');
  assert.equal(tomb.match,'exact');
  assert.equal(core.resolveRivenWeapon('Tombfinger').canonical,'Tombfinger');
  assert.equal(core.resolveRivenWeapon('tOmBfInGeR').canonical,'Tombfinger');
  for(const query of ['diyinbaonang','di yin bao nang','di-yin-bao-nang']){
    const bassocyst=core.resolveRivenWeapon(query);
    assert.equal(bassocyst.canonical,'Coda Bassocyst');
    assert.equal(bassocyst.displayName,'终幕·低音爆囊');
    assert.equal(bassocyst.match,'pinyin-exact');
  }
})
test('WFM 当前 Riven 目录系统覆盖模块化主部件并排除非市场组件',()=>{
  const market=require('../knowledge/supplemental/riven-market-weapons.json');
  for(const [group,family,role,count] of [['zaw','zaw','strike',11],['kitgun','kitgun','chamber',6]]){
    const expected=market.entries.filter(item=>item.group===group);assert.equal(expected.length,count);
    for(const item of expected){const resolved=core.resolveRivenWeapon(item.canonical);assert.equal(resolved.officialUniqueName,item.gameRef,item.canonical);assert.equal(resolved.marketSlug,item.slug);assert.equal(resolved.modularFamily,family);assert.equal(resolved.componentRole,role);if(group==='kitgun'){assert.deepEqual(resolved.dispositions,item.dispositions);assert.equal(core.getRivenWeapon(item.gameRef).omegaAttenuation,null)}else assert.equal(core.getRivenWeapon(item.gameRef).omegaAttenuation,item.disposition)}
  }
  for(const [query,canonical,display] of [['Mewan','Mewan','密丸'],['密丸','Mewan','密丸'],['miwan','Mewan','密丸'],['Sepfahn','Sepfahn','瑟普梵'],['瑟普梵','Sepfahn','瑟普梵'],['sepufan','Sepfahn','瑟普梵']]){const resolved=core.resolveRivenWeapon(query);assert.equal(resolved.canonical,canonical,query);assert.equal(resolved.displayName,display,query)}
  for(const query of ['Ekwana Jai II','Seekalla','Lohrin','Raplak Prism']){const rejected=core.resolveRivenWeapon(query);assert.ok(!rejected||rejected.ambiguous,query)}
  for(const query of ['Khra','Xata']){const rejected=core.resolveRivenWeapon(query);assert.ok(!rejected||rejected.ambiguous,query)}
  assert.equal(market.entries.filter(item=>item.group==='amp').length,0);
  const kitguns=market.entries.filter(item=>item.group==='kitgun');assert.equal(kitguns.length,6);assert.ok(kitguns.every(item=>Object.values(item.dispositions||{}).some(Number.isFinite)));assert.ok(kitguns.filter(item=>Number.isFinite(item.dispositions?.primary)&&Number.isFinite(item.dispositions?.secondary)).every(item=>item.dispositions.primary!==item.dispositions.secondary));
})
test('冰凇按官方简中、英文和全拼绑定 WFM 稳定身份，冲突首字母不擅选',()=>{
  for(const [query,match] of [['冰凇','exact'],['Verglas','exact'],['vErGlAs','exact'],['bingsong','pinyin-exact'],['BING SONG','pinyin-exact']]){
    const resolved=core.resolveRivenWeapon(query);assert.equal(resolved.canonical,'Verglas',query);assert.equal(resolved.displayName,'冰凇',query);assert.equal(resolved.officialUniqueName,'/Lotus/Types/Sentinels/SentinelWeapons/SentinelFreezeRayRifle',query);assert.equal(resolved.marketSlug,'verglas',query);assert.equal(resolved.marketGroup,'sentinel',query);assert.equal(resolved.match,match,query)
  }
  const initials=core.resolveRivenWeapon('bs');assert.equal(initials.reason,'pinyin-initials-collision');assert.deepEqual(new Set(initials.ambiguous.map(item=>item.canonical)),new Set(['Verglas','Sporelacer']));
})
test('紫卡武器前缀只在审核精确边界消费名称',()=>{
  const spaced=core.resolveRivenWeaponPrefix('托里德 暴伤 多重 基伤 负投射物');
  assert.equal(spaced.weaponQuery,'托里德');assert.equal(spaced.remainder,'暴伤 多重 基伤 负投射物');assert.equal(spaced.resolution.canonical,'Torid');
  const compact=core.resolveRivenWeaponPrefix('Torid暴伤多重');assert.equal(compact.weaponQuery,'Torid');assert.equal(compact.remainder,'暴伤多重');
  const multi=core.resolveRivenWeaponPrefix('Coda Bassocyst critical damage');assert.equal(multi.weaponQuery,'Coda Bassocyst');assert.equal(multi.resolution.canonical,'Coda Bassocyst');
  const modular=core.resolveRivenWeaponPrefix('wenyikelipasi暴伤');assert.equal(modular.weaponQuery,'wenyikelipasi');assert.equal(modular.remainder,'暴伤');assert.equal(modular.resolution.canonical,'Plague Kripath');
})
test('紫卡武器中文和拼音模糊匹配执行置信度与领先差门槛',()=>{
  assert.equal(core.resolveRivenWeapon('终幕低音爆袋').canonical,'Coda Bassocyst');
  assert.equal(core.resolveRivenWeapon('diyinbaonag').canonical,'Coda Bassocyst');
  const low=core.resolveRivenWeapon('diyin');
  assert.ok(Array.isArray(low.ambiguous));
  assert.equal(low.reason,'low-confidence');
  assert.ok(low.ambiguous.length>=1);
  assert.equal(low.ambiguous[0].displayName,'终幕·低音爆囊');
  const multi=core.resolveRivenWeapon('shiren');
  assert.ok(Array.isArray(multi.ambiguous));
  assert.equal(multi.reason,'pinyin-collision');
  assert.ok(multi.ambiguous.length>=2);
})
test('全量武器家族按类别约束解析前后置与粘连语法',()=>{
  for(const [query,canonical] of [['莲花凯旋','Imperator Vandal'],['凯旋 莲花','Imperator Vandal'],['凯旋将军 破坏者','Imperator Vandal'],['集团 执法者','Sancti Magistar'],['执法者 圣洁','Sancti Magistar'],['奸商什长双枪','Prisma Dual Decurions'],['斩肉双刀奸商','Prisma Dual Cleavers'],['亡魂 拉特昂','Latron Wraith'],['赤毒沙皇','Kuva Zarr']]){
    const result=core.resolveWeaponVariantIntent(query);assert.equal(result.identity.canonical,canonical,query);assert.equal(result.ambiguous,false,query)
  }
  const family=core.getWeaponVariantFamily('马谢特砍刀');assert.deepEqual(new Set(family.members.map(item=>item.canonical)),new Set(['Machete','Prisma Machete','Machete Wraith']));
  assert.ok(Object.keys(core.weaponVariantIntentAliases).length>=10)
})
test('紫卡按变体家族归一但只使用 WFM Riven 目录事实',()=>{for(const query of ['莲花凯旋','凯旋将军 破坏者']){const riven=core.resolveRivenWeaponFamilyIntent(query);assert.equal(riven.canonical,'Imperator');assert.equal(riven.marketSlug,'imperator');assert.equal(riven.familyNormalized,true)}})
test('武器解析使用共享评分器，合成支持多个输入和名称标点',()=>{assert.equal(core.resolveWeapon('骄傲').canonical,'Pride');const parsed=core.parseWeaponCraftingCommand('合成 骄傲、Cernos');assert.equal(parsed.items.length,2);assert.doesNotMatch(core.renderWeaponCraftingCommand('合成 骄傲'),/如何合成|制造费用|耗时|【/);assert.equal(core.parseWeaponCraftingCommand('今天合成点什么'),null)})
test('官方任务表按每个任务标题切换，不把骄傲错误继承到水星',()=>{const pride=core.getWeapon('骄傲'),blueprint=pride.acquisition.routes.find(x=>x.scope==='blueprint');assert.ok(blueprint.methods.some(x=>x.sourceCanonical==='Uranus/The Kuva Wytch (Skirmish)'&&x.locationId==='mission.the-kuva-wytch'&&x.missionTypeId==='mission-type.skirmish'&&x.chance===0.1429));assert.ok(blueprint.methods.every(x=>x.sourceCanonical!=='Mercury/Apollodorus (Survival)'))})
test('骄傲由舰船任务和 Hunhow 官方报价完整闭环',()=>{const pride=core.getWeapon('骄傲'),result=core.getAcquisition('骄傲');assert.equal(pride.status,'complete');const blueprint=pride.acquisition.routes.find(x=>x.scope==='blueprint'),exchange=blueprint.methods.find(x=>x.type==='vendor-exchange'),structured=result.structuredMethods.find(x=>x.type==='vendor-exchange'&&x.scope==='blueprint');assert.equal(exchange.npcId,'npc.hunhow');assert.equal(exchange.locationId,'hub.pontis-tower');assert.equal(exchange.requirements.currency[0].currencyId,'currency.emerald-talent');assert.equal(exchange.requirements.currency[0].amount,90);assert.equal(structured.npcId,'npc.hunhow');assert.equal(structured.locationId,'hub.pontis-tower');assert.deepEqual(structured.requirements.currency,[{currencyId:'currency.emerald-talent',amount:90}]);assert.equal(structured.requirementLines[0],'在渡界之塔的Hunhow处消耗90个翠绿天赋兑换');assert.match(result.description,/总图及握柄、刀刃：完成赤毒女巫号（前哨战）概率获得/);assert.match(result.description,/总图：在渡界之塔的Hunhow处消耗90个翠绿天赋兑换/);assert.match(result.description,/愤怒 刀刃：完成火山石天使号（前哨战）、赤毒女巫号（前哨战）概率获得/);assert.doesNotMatch(result.description,/水星|边界之塔/)})
test('禁止依据 excludeFromMarket 猜商城来源或完整状态',()=>{const braton=core.getWeapon('布莱顿'),blueprint=braton.acquisition.routes.find(x=>x.scope==='blueprint');assert.equal(braton.status,'complete');assert.equal(blueprint,undefined);assert.equal(braton.acquisition.routes.find(x=>x.scope==='item').methods[0].provenance.source,'local-wiki-sqlite');assert.doesNotMatch(core.getAcquisition('布莱顿').description,/尚未由 DE 官方结构闭环/);assert.match(core.getAcquisition('布莱顿').description,/成品：在商店购买/)})
test('舍杜由官方任务、掉落表、配方和简中描述闭环',()=>{const shedu=core.getWeapon('舍杜'),result=core.getAcquisition('舍杜');assert.equal(shedu.status,'complete');assert.equal(shedu.description.localizationStatus,'official-zh');assert.equal(shedu.acquisition.routes.find(x=>x.scope==='blueprint').methods[0].questCanonical,'Erra');const parts=shedu.acquisition.routes.filter(x=>x.scope==='component');assert.equal(parts.length,4);assert.ok(parts.every(x=>x.status==='complete'&&x.methods[0].sourceEntityId==='enemy.symbilyst'&&x.methods[0].chance===0.01));assert.match(result.description,/总图：完成任务「Erra」获得/);assert.match(result.description,/舍杜 枪管、机体、握柄、枪机：击败共生使概率获得/);assert.doesNotMatch(result.description,/尚未由 DE 官方结构闭环/)})
test('葬铭从官方虚空风暴奖励补充表编译总图与部件来源',()=>{const epitaph=core.getWeapon('葬铭'),result=core.getAcquisition('葬铭');const blueprint=epitaph.acquisition.routes.find(x=>x.scope==='blueprint'),parts=epitaph.acquisition.routes.filter(x=>x.scope==='component');assert.equal(blueprint.status,'complete');assert.equal(parts.length,2);assert.ok(parts.every(x=>x.status==='complete'));assert.match(result.description,/总图与部件：完成九重天地球、金星、土星比邻星虚空风暴概率获得/);assert.doesNotMatch(result.description,/9\.52%|10%|葬铭 枪管|葬铭 枪机/);assert.doesNotMatch(result.description,/WraithSidearm/)});
test('暮斩总图锁定扎里曼赏金且任务节点不泄漏英文类型括注',()=>{const text=core.getAcquisition('暮斩').description,weapon=core.getWeapon('暮斩'),blueprint=weapon.acquisition.routes.find(route=>route.scope==='blueprint').methods[0];assert.equal(blueprint.locationId,'bounty.zariman');assert.equal(blueprint.missionTypeId,'mission-type.bounty');assert.match(text,/总图：从扎里曼号赏金奖励中获得/);assert.match(text,/奥金工场（虚空决战） C轮/);assert.match(text,/涂沃主厅（虚空覆涌） C轮/);assert.doesNotMatch(text,/夜灵平野|Void Armageddon|Void Cascade/)});
test('开放世界赏金区全量编译并合并同地点多阶段记录',()=>{const drops=require('../generated/official-drop-table-index.json').byItem['Verdilac Blueprint'],weapon=core.getWeapon('蝰首骨妖'),text=core.getAcquisition('蝰首骨妖').description;assert.equal(drops.length,4);assert.ok(drops.every(drop=>drop.provenance.section==='Bounty Rewards'&&drop.stage));assert.equal(weapon.status,'complete');assert.match(text,/总图：从合一众赏金奖励中获得/);assert.equal((text.match(/^总图：/gm)||[]).length,1);assert.doesNotMatch(text,/%|尚未由 DE 官方结构闭环/)});
test('官方部件内部 ID 按公开后缀与 CraftingComponents 语言键系统挂接',()=>{const corufell=core.getWeapon('闪劫'),vesper=core.getWeapon('夜语者 77');assert.equal(corufell.recipes[0].ingredients[0].displayName,'闪劫 枪管');assert.ok(corufell.acquisition.routes.find(route=>route.partRefs.includes('/Lotus/Types/Recipes/Weapons/WeaponParts/GunScytheBlade')).methods.some(method=>method.sourceCanonical==='Mars/Tyana Pass (Defense)'));assert.equal(vesper.recipes[0].ingredients[2].displayName,'夜语者 77 握柄');assert.ok(vesper.acquisition.routes.find(route=>route.partRefs.includes('/Lotus/Types/Recipes/Weapons/WeaponParts/LasSilencedPistolStock')).methods.length>0)});
test('武器隐藏概率时同一总图的替代敌人合并为一行且底层概率保持独立',()=>{const weapon=core.getWeapon('阿利乌双枪'),text=core.getAcquisition('阿利乌双枪').description,drops=weapon.acquisition.routes.find(route=>route.scope==='blueprint').methods;assert.equal(drops.length,4);assert.equal(new Set(drops.map(method=>method.chance)).size,2);assert.match(text,/总图：击败爆破型痈裂者、爆破型奔跳者、爆破型巨兽、爆破型疾冲者概率获得/);assert.equal((text.match(/^总图：/gm)||[]).length,1);assert.doesNotMatch(text,/%/) });
test('Prime 武器复用状态框架且特殊 Prime 不伪装成遗物来源',()=>{const current=core.getWeapon('塞多 Prime'),currentText=core.getAcquisition('塞多 Prime').description,vaulted=core.getWeapon('黑鸦 Prime'),vaultedText=core.getAcquisition('黑鸦 Prime').description,sagek=core.getWeapon('杀格 Prime'),sagekText=core.getAcquisition('杀格 Prime').description;assert.equal(current.acquisition.prime.kind,'prime-relic');assert.equal(current.acquisition.prime.status,'当前出库');assert.match(currentText,/Prime 状态：当前出库/);assert.match(currentText,/总图：中纪 C9（金）/);assert.match(currentText,/枪机：古纪 K12（银）；古纪 Q3（银）/);assert.equal(vaulted.acquisition.prime.status,'已入库');assert.match(vaultedText,/当前已入库/);assert.equal(sagek.acquisition.prime.kind,'special-prime');assert.match(sagekText,/佩里塔叛乱/);assert.doesNotMatch(sagekText,/遗物|已入库|Prime 状态/)});
test('刷武器不把空泛制造句当作获取来源且合成指令不显示制作配方',()=>{for(const entry of core.weapons){const output=core.getAcquisition(entry.subject.canonical).description;assert.doesNotMatch(output,/(?:^|\n)制造[^\n]+/)}assert.equal(core.renderWeaponCraftingCommand('合成 葬铭'),'这些武器不能用于合成其他武器')})
test('随装备附带的武器使用明确动作条件且禁止病句',()=>{const mausolon=core.getWeapon('惩戒者'),result=core.getAcquisition('惩戒者'),method=result.structuredMethods.find(item=>item.type==='included-with-equipment');assert.equal(mausolon.subject.canonical,'Mausolon');assert.equal(mausolon.subject.officialUniqueName,'/Lotus/Weapons/Tenno/Archwing/Primary/ThanoTechArchLongGun/ThanoTechLongGun');assert.equal(mausolon.weaponIdentity.equipmentType,'arch-gun');assert.deepEqual(method.variables.equipmentOptions,['虚空锐将','骨骸寡妇']);assert.equal(method.variables.acquisitionAction,'claim-from-foundry');assert.match(result.description,/成品：从铸造厂领取已建成的虚空锐将或骨骸寡妇殁世机甲时自动获得（已安装重力磁抵器）/);for(const entry of core.weapons){const output=core.getAcquisition(entry.subject.canonical).description;assert.doesNotMatch(output,/达到.+时获得/,entry.subject.canonical)}})
test('Simaris 武器来源从原始分类全量编译且未知规则保持待审',()=>{const index=require('../generated/simaris-weapon-source-index.json');assert.equal(index.counts.weapons,18);assert.equal(index.counts.records,21);assert.equal(index.counts.approved,13);assert.equal(index.counts.reviewRequired,8);for(const records of Object.values(index.byWeapon))for(const record of records){assert.match(record.sourceCanonical,/^Cephalon Simaris/);if(record.reviewStatus==='approved'){assert.equal(record.kind,'quest-repurchase');assert.ok(record.unlockId&&record.unlockDisplayName)}else assert.ok(['standing-shop','daily-tribute-repurchase','glassmaker-repurchase','unresolved-simaris'].includes(record.kind))}})
test('全部已批准 Simaris 武器记录均接入对应层级的任务首获和后续回购',()=>{const index=require('../generated/simaris-weapon-source-index.json');for(const records of Object.values(index.byWeapon)){const approved=records.filter(record=>record.reviewStatus==='approved');if(!approved.length)continue;const weapon=core.getWeapon(approved[0].weaponCanonical);if(!weapon)continue;for(const record of approved){const route=weapon.acquisition.routes.find(candidate=>candidate.scope===record.scope&&(!record.partUniqueName||candidate.partRefs.includes(record.partUniqueName)));assert.ok(route,`${record.weaponCanonical} ${record.scope} 缺 route`);assert.ok(route.methods.some(method=>method.type==='quest-reward'&&method.questId===record.unlockId));assert.ok(route.methods.some(method=>method.type==='vendor-exchange'&&method.npcId==='npc.cephalon-simaris'))}}const natarukResult=core.getAcquisition('太始弓'),nataruk=natarukResult.description;assert.match(nataruk,/成品：完成任务「新纪之战」获得/);assert.doesNotMatch(nataruk,/中枢 Simaris处兑换/);assert.ok(natarukResult.structuredMethods.some(method=>method.type==='vendor-exchange'&&method.reviewStatus==='review-required'&&method.reviewIssues.includes('amount')))})
test('DE 官方支持文档任务武器全部接入首获路线而不是逐武器补丁',()=>{const index=require('../generated/official-support-quest-weapon-index.json');assert.equal(index.counts.weapons,13);for(const records of Object.values(index.byWeapon))for(const record of records){const weapon=core.getWeapon(record.weaponCanonical),scopes=record.scope==='blueprint-and-components'?['blueprint',...weapon.acquisition.routes.filter(route=>route.scope==='component').map(()=> 'component')]:[record.scope];for(const scope of new Set(scopes)){const routes=weapon.acquisition.routes.filter(route=>route.scope===scope);assert.ok(routes.some(route=>route.methods.some(method=>method.type==='quest-reward'&&method.questId===`quest.${record.questCanonical.normalize('NFKD').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}`)),`${record.weaponCanonical} 缺 ${record.questDisplayName} ${scope} 路线`)}}const broken=core.getAcquisition('破碎的战争之剑').description;assert.match(broken,/成品：完成任务「第二场梦」获得/);assert.match(broken,/总图：击败黑影追猎者、卫护追猎者概率获得/);assert.doesNotMatch(broken,/尚未由 DE 官方结构闭环：成品来源/)});
test('驱魔之刃完整显示僵局协议首获与 Simaris 后续回购',()=>{const xoris=core.getWeapon('驱魔之刃'),text=core.getAcquisition('驱魔之刃').description,craft=core.renderWeaponCraftingCommand('合成 驱魔之刃');assert.equal(xoris.status,'complete');assert.ok(xoris.acquisition.routes.filter(route=>['blueprint','component'].includes(route.scope)).every(route=>route.status==='complete'&&route.methods.some(method=>method.type==='quest-reward')&&route.methods.some(method=>method.type==='vendor-exchange')));assert.match(text,/总图与部件：完成任务「僵局协议」获得；完成后可在任意中继站找中枢 Simaris 回购（总图 100,000 声望，各部件 15,000 声望）/);assert.doesNotMatch(text,/尚未由 DE 官方结构闭环|CrpGhostCatcher/);assert.equal(craft,'这些武器不能用于合成其他武器')})
test('完整性只由统一官方证据闭环决定而不使用武器名白名单',()=>{const complete=core.weapons.filter(entry=>entry.status==='complete');assert.ok(complete.length>100);for(const entry of core.weapons){assert.equal(entry.status==='complete',entry.coverage.autoComplete);assert.equal(entry.coverage.auditedComplete,entry.coverage.autoComplete);if(entry.coverage.autoComplete)assert.deepEqual(entry.reviewedBy,['official-evidence-closure'])}const akarius=core.getWeapon('阿利乌双枪'),text=core.getAcquisition('阿利乌双枪').description;assert.equal(akarius.status,'complete');assert.doesNotMatch(text,/自动闭环.*待审|尚未由 DE 官方结构闭环/)});
test('全量武器明确记录描述与适用获取链缺口但运行时不泄漏维护清单',()=>{for(const entry of core.weapons){assert.ok(entry.coverage&&typeof entry.coverage.description==='boolean');assert.ok(Array.isArray(entry.coverage.components));const output=core.getAcquisition(entry.subject.canonical).description;assert.doesNotMatch(output,/尚未由 DE 官方结构闭环|ExportWeapons 尚未提供|official-zh-unavailable|review-required|\/Lotus\//)}})
test('怒斩由统一 Wiki 获取编译器接入道场总图和全部部件',()=>{const entry=core.getWeapon('怒斩'),text=core.getAcquisition('怒斩').description,routes=entry.acquisition.routes.filter(route=>['blueprint','component'].includes(route.scope));assert.equal(routes.length,5);assert.ok(routes.every(route=>route.status==='complete'&&route.methods.some(method=>method.type==='dojo-research'&&method.provenance.source==='local-wiki-sqlite')));assert.match(text,/总图：在氏族道场「Dagath 的空阁」复制蓝图/);assert.match(text,/怒斩 刀刃：在氏族道场「Dagath 的空阁」复制蓝图/);assert.doesNotMatch(text,/尚未由 DE 官方结构闭环/)})
test('双衍王境近战总图统一保留 Teshin 洞穴苦栓价格',()=>{const result=core.getAcquisition('三宝聚'),method=result.structuredMethods.find(item=>item.type==='vendor-exchange'&&item.scope==='blueprint');assert.equal(method.reviewStatus,'approved');assert.equal(method.sourceEntityId,'acquisition-source.teshins-cave');assert.deepEqual(method.requirements.currency,[{currencyId:'currency.pathos-clamp',amount:60}]);assert.match(method.requirementLines[0],/60个苦栓/);assert.match(result.description,/总图：在双衍王境的Teshin 的洞穴处消耗60个苦栓兑换/);assert.doesNotMatch(result.description,/尚未由 DE 官方结构闭环/)})
test('武器审计逐把检查真实输出并拒绝内部字段',()=>{const audit=require('../scripts/audit-weapon-coverage'),built=audit.build('test');assert.equal(built.counts.weapons,core.weapons.length);assert.equal(built.counts.publishable+built.counts.failed,built.counts.weapons);assert.deepEqual(audit.outputIssues('正常中文说明。'),[]);assert.ok(audit.outputIssues('尚未由 DE 官方结构闭环：总图来源。').includes('internal-or-review-text-exposed'))})
test('所有武器 route 与已装配 method 只使用共享 requirements 且不泄漏未本地化来源',()=>{for(const entry of core.weapons){for(const route of entry.acquisition.routes){assert.ok(route.requirements);assert.ok(['none','currency','standing','quest','item'].includes(route.requirements.type));for(const method of route.methods||[])if(method.reviewStatus==='approved'&&method.sourceCanonical)assert.ok(method.sourceDisplayName||method.locationId||method.sourceEntityId||method.npcId||method.questId||method.factionId||method.factionIds?.length)}const result=core.getAcquisition(entry.subject.canonical);assert.ok(result);assert.ok(result.structuredMethods.every(m=>m.requirements&&Array.isArray(m.requirementLines)))}})
